import { FOREVER_UNLOCK_AT } from '../../config'
import type { World } from '../../types/world'

// Local mock, shaped like the future API. Replaced by experienceApi.getWorlds later.
export const WORLDS_MOCK: readonly World[] = [
  {
    id: 1,
    slug: 'where-it-all-began',
    title: 'Where It All Began',
    subtitle: 'The first hello, and everything that quietly followed.',
    layout: 'polaroid',
    tint: ['#f3c9cf', '#b3122f'],
    photoCount: 24,
    locked: false,
    unlockAt: null,
  },
  {
    id: 2,
    slug: 'our-firsts',
    title: 'Our Firsts',
    subtitle: 'First trips, first laughs, first of many.',
    layout: 'filmstrip',
    tint: ['#f6d7b8', '#c4402f'],
    photoCount: 31,
    locked: false,
    unlockAt: null,
  },
  {
    id: 3,
    slug: 'adventures-together',
    title: 'Adventures Together',
    subtitle: 'Postcards from everywhere we have been.',
    layout: 'postcards',
    tint: ['#c9d9e8', '#7a1f3d'],
    photoCount: 42,
    locked: false,
    unlockAt: null,
  },
  {
    id: 4,
    slug: 'little-everyday-moments',
    title: 'Little Everyday Moments',
    subtitle: 'The ordinary days that turned out to be the best ones.',
    layout: 'memorywall',
    tint: ['#efd5e2', '#a3204a'],
    photoCount: 58,
    locked: false,
    unlockAt: null,
  },
  {
    id: 5,
    slug: 'the-question',
    title: 'The Question',
    subtitle: 'One evening, one ring, one yes.',
    layout: 'envelope',
    tint: ['#f7e3c4', '#8f1226'],
    photoCount: 12,
    locked: false,
    unlockAt: null,
  },
  {
    id: 6,
    slug: 'our-forever',
    title: 'Our Forever',
    subtitle: 'A sky of stars we have not written yet.',
    layout: 'constellation',
    tint: ['#2a1b4d', '#e50914'],
    photoCount: 0,
    locked: true,
    unlockAt: FOREVER_UNLOCK_AT,
  },
]
