-- Phase 1: imported media and import jobs. World/moment/letter/settings tables arrive in Phase 2.
CREATE TABLE media (
    id              VARCHAR(26)  NOT NULL PRIMARY KEY,
    google_media_id VARCHAR(512) NOT NULL,
    mime_type       VARCHAR(100),
    width           INT,
    height          INT,
    taken_at        TIMESTAMP WITH TIME ZONE,
    filename        VARCHAR(512),
    lqip            VARCHAR(20000),
    dominant_color  VARCHAR(7),
    has_video       BOOLEAN      DEFAULT FALSE NOT NULL,
    imported_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_media_google_media_id UNIQUE (google_media_id)
);
CREATE INDEX idx_media_imported ON media (imported_at DESC, id DESC);

CREATE TABLE import_job (
    id                VARCHAR(26)  NOT NULL PRIMARY KEY,
    picker_session_id VARCHAR(512) NOT NULL,
    status            VARCHAR(16)  NOT NULL,
    total             INT          DEFAULT 0 NOT NULL,
    done              INT          DEFAULT 0 NOT NULL,
    failed            INT          DEFAULT 0 NOT NULL,
    skipped           INT          DEFAULT 0 NOT NULL,
    error             VARCHAR(1000),
    started_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at       TIMESTAMP WITH TIME ZONE
);

CREATE TABLE import_job_failure (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id          VARCHAR(26)  NOT NULL,
    google_media_id VARCHAR(512),
    filename        VARCHAR(512),
    outcome         VARCHAR(8)   NOT NULL,
    reason          VARCHAR(200) NOT NULL,
    CONSTRAINT fk_failure_job FOREIGN KEY (job_id) REFERENCES import_job (id) ON DELETE CASCADE
);
CREATE INDEX idx_failure_job ON import_job_failure (job_id);
